#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : sshpass
Version  : 1.09
Release  : 5
URL      : https://mirrors.kernel.org/debian/pool/main/s/sshpass/sshpass_1.09.orig.tar.gz
Source0  : https://mirrors.kernel.org/debian/pool/main/s/sshpass/sshpass_1.09.orig.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: sshpass-bin = %{version}-%{release}
Requires: sshpass-license = %{version}-%{release}
Requires: sshpass-man = %{version}-%{release}

%description


%package bin
Summary: bin components for the sshpass package.
Group: Binaries
Requires: sshpass-license = %{version}-%{release}

%description bin
bin components for the sshpass package.


%package license
Summary: license components for the sshpass package.
Group: Default

%description license
license components for the sshpass package.


%package man
Summary: man components for the sshpass package.
Group: Default

%description man
man components for the sshpass package.


%prep
%setup -q -n sshpass-1.09
cd %{_builddir}/sshpass-1.09

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1661368958
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1661368958
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/sshpass
cp %{_builddir}/sshpass-%{version}/COPYING %{buildroot}/usr/share/package-licenses/sshpass/dfac199a7539a404407098a2541b9482279f690d
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/sshpass

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/sshpass/dfac199a7539a404407098a2541b9482279f690d

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/sshpass.1
